### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Amitasulin9** [Amitasulin9/Off-The-record#3]
יש לעבור על האיפיאי של כיכר המדינה ושל פייסבוק לשם הסקת מסקנות אלגוריתמיות לשם תכנון אלגוריתמי של הפרוייקט

**Comment by Amitasulin9** [comment]
ניר שלום 
נא לעדכן איפה הדברים עומדים 
תודה

**Comment by nir-jackson** [comment]
בוצע,

הכנתי URL פשוט ונוח לשימוש, שכל מה שאלכס צריך לעשות זה לגשת אליהם,

להלן URL שמסודרים לפי פוליטיקאי:

יאיר לפיד:
https://graph.facebook.com/yairlapid?fields=posts.limit(250){message}&access_token=CAACEdEose0cBAJ5YIbSJea0EnZBQpuhDkEBoz8qyVEPo8ZBzRmZBkfrY04cjSmR48TgunU81U09QY2ZBEjsH0frcsNX2ZCgvZBhXzZATruo9YGlZARJ1SfZADfko8JgUUey5y5Sm4NB107EDoYx47GblvLYWO9oGlqhgEFSK6azU7GI2kOtyVAhcQR45MrUA6RfTdwXjCS0A2QsrNtNwG7qHZA890eZCuXihZBIZD

בנימין נתניהו:
https://graph.facebook.com/Netanyahu?fields=posts.limit(250){message}&access_token=CAACEdEose0cBAJ5YIbSJea0EnZBQpuhDkEBoz8qyVEPo8ZBzRmZBkfrY04cjSmR48TgunU81U09QY2ZBEjsH0frcsNX2ZCgvZBhXzZATruo9YGlZARJ1SfZADfko8JgUUey5y5Sm4NB107EDoYx47GblvLYWO9oGlqhgEFSK6azU7GI2kOtyVAhcQR45MrUA6RfTdwXjCS0A2QsrNtNwG7qHZA890eZCuXihZBIZD

****חדי עין ישימו לב שכל ההבדל הוא בפרמטר הראשוני לכן מכאן אפשר לעשות העתק הדבק לשמות הבאים:

בנט: NaftaliBennett
ציפי לבני: tzipilivni
יצחק הרצוג: IsaacHerzogKneset
אביגדור ליברמן: AvigdorLiberman
משה כחלון: Moshekahalon
דני דנון: DanonDanny
אריה דרעי: DeryArye
עמיר פרץ: Peretz.Amir

כמובן שיש עוד הרבה פוליטיקאים וכל מי שאתם חושבים שאני צריך להוסיף תגידו

**Comment by Amitasulin9** [comment]
אחלה ניר 
אשלח לך את הרשימה המלאה

**Comment by AlexGr2** [comment]
הי ניר, השתמשת בטוקן שהוא זמני עכשיו כל הסט הוא לא זמין לעבודה
בבקשה תתקן את זה אני לא יכול להמשיך בלי דאטא

**Comment by nir-jackson** [comment]
permanent access token:
1719315164960950|nKFpk2SebwixsCQS3y7zQDPA1Ow

example of an URL:  https://graph.facebook.com/Netanyahu?fields=posts.limit(250){message}&access_token=1719315164960950|nKFpk2SebwixsCQS3y7zQDPA1Ow
