### ISSUE TITLE
DB Queries

### ISSUE THREAD

**Issue by Amitasulin9** [Amitasulin9/Off-The-record#4]
הפעלת שאילתות על מסד הנתונים שהתקבל מיותם (סי.אס.וי) לבדיקת:
המילה הנפוצה ביותר שנכתבת ע״י כל פוליטיקאי-
מה הפיזור של המילה הנפוצה על ציר הזמן- רק מבחינת תאריכים-
מהן חמשת המילים הנפוצות ביותר לכל פוליטיקאי-

**Comment by Amitasulin9** [comment]
אהלן אלכס 
בבקשה עדכן אותנו איפה עומדים הדברים 
על מנת שנוכל להתקדם 

אחלה יום :)

**Comment by AlexGr2** [comment]
אהלן, אני כרגע עובדת על אימפלימנציה של 
webapp 
מכיוון שאנחנו לא עושים 
website 
אנחנו צריכים מדול 
wrapper
שיצור עמודים 
html 
דינאמת
