### ISSUE TITLE
FaceBook call Limit

### ISSUE THREAD

**Issue by nir-jackson** [Amitasulin9/Off-The-record#9]
Facebook doesn't allow you to make more than 600 calls in 600 seconds.

We call facebook to get the posts (messages). every post is 1 call. 
so for instance if you search a word and click on a politician who said that word 10 times the system will make 10 FB Api calls.

my recomendation:
Batch all the requests together. 
facebook allows us to create a JSON file with all the calls we need to make and send that as one call. 
facebook will respond with one JSON accordingly. according to facebook documentary we can make up to 50 api calls in one batch.

**Comment by mushon** [comment]
This makes sense to me and I see no down side in taking that approach. I will also consult with @yotammanor on the issue later today.

**Comment by mushon** [comment]
ok,
I just spoke with Yotam and we agreed that an API call to Kikar Hamedina will make sure no limit is imposed on you. I would suggest to do two things:
1. try to see whether the batch solves the problem
2. Write code that calls Kikar Hamedina's API as a fallback plan
3. Credit Hasadna's Kikar Hamedina project and Yotam for their help, support and inspiration

@yotammanor will later comment with an example for an API call 

I'm very excited about your project and can't wait to see it live.

cc: @akariv @shaulams @amnoid @Amitasulin9 @eldadtzadok @moranbz @AlexGr2

**Comment by yotammanor** [comment]
Hi everyone, I hope you're doing well.

To get all statuses by feed id, you call for this:

http://kikar.hasadna.org.il/api/v1/facebook_status/?feed=15&format=json

since feed id is an internal key, I attached a table that maps feed id to
candidate name and party.
(If the attachment doesn't come through let me know)

**Comment by nir-jackson** [comment]
@yotammanor Hey!
thank you for agreeing to help me with this project.
the link you shared here sends me to a json that the "content" tag is written in gibberish. 
the reason i decided that i want to work with facebook in the first place was because they have detailed documentation on their API and how it works. in order for me to use kikar's API i'm going to need help understanding how to use it. i had a hard time figuring it out by myself the last time.

regards

**Comment by yotammanor** [comment]
The gibberish is because of your browser. Save it to a file and you'll see
that it works well.

**Comment by nir-jackson** [comment]
ok, you're right thanks :)

can we meet and you could show me how to integrate your API into my javascript code?

**Comment by yotammanor** [comment]
I'm during the height of my exam period, and I don't think you can afford
to wait for me, nor do I think you should.
I'm available by phone and email for any particular question, but as I
wrote -

http://kikar.hasadna.org.il/api/v1/facebook_status/
http://kikar.hasadna.org.il/api/v1/facebook_status/?feed=15&format=json -
is the api request you send in order to get statuses, which what I
understand you plan to use.

arguments:
feed_id=5 - filter by feed id. the excel I sent you will tell you which id
maps to which page.
limit=20 - number of posts per request
offset=20 - start at post number 20.
format=json - always add this

anything else, just ask me.

**Comment by nir-jackson** [comment]
ok, lets say i want to get a specific status (post) using its id.
for example:

i want to get a specific post by Aryeh Deri, all i know is its ID.
For Example 433095953410548_589724194414389.
how do i get that specific post using your api?

**Comment by mushon** [comment]
@yotammanor ^

**Comment by nir-jackson** [comment]
@yotammanor hey,

i'm a little with making api calls to get the information i need, when you have the time please answer my previous question.

**Comment by mushon** [comment]
@nir-jackson, come tomorrow to our hackaton:
http://www.hasadna.org.il/%D7%90%D7%99%D7%A8%D7%95%D7%A2%D7%99%D7%9D-2/%D7%94%D7%90%D7%A7%D7%AA%D7%95%D7%9F-%D7%91%D7%97%D7%99%D7%A8%D7%95%D7%AA-2015/

We can probably solve things better looking at the same screen.

**Comment by nir-jackson** [comment]
hey.
i can't make it on Saturday.
i'm actually not having trouble with most of the functions. 

i asked a very strait forward question 
if i'm going to use the kikar hamedina API i just need an example of how to get a specific post.

please answer the question i asked before and everything will be allright

**Comment by mushon** [comment]
@yotammanor, can you give us an example of an API call to get a status by it ID? This would be pretty much everything needed from Nir's side. 

Cc: @akariv

**Comment by nir-jackson** [comment]
hey yotam, 
can you resend me the excel please?
thanks
@yotammanor

**Comment by yotammanor** [comment]
API call for a unique status by id:

http://kikar.hasadna.org.il/api/v1/facebook_status/?status_id=310448006908_10152361169771909

the excel is reattached.

enjoy

**Comment by nir-jackson** [comment]
Thanks!
That's Great! :smile: 
i still can't see the excel please send it to nir.jackson89@gmail.com (although i don't need it).
you solved a lot of my problems. thank you very very much.

**Comment by yotammanor** [comment]
Your welcome.

Don't forget to link back to http://kikar.org :)

**Comment by mushon** [comment]
That’s great @yotammanor, thanks so much!

@Amitasulin9 @eldadtzadok @moranbz please make sure to add the proper credit:
הפרויקט עושה שימוש בנתונים מפייסבוק ובנתוני אתר [כיכר המדינה](http://kikar.org) של [הסדנא לידע ציבורי](http://hasadna.org)

בנוסף אני חושב שמן הראוי לציין תודה אישית ליותם מנור על העזרה והמענה.
(ואל תשכחו גם את הקרדיטים להנחיה הן לשאול אמסטרדמסקי והן לאדם קריב)

בהצלחה!

**Comment by nir-jackson** [comment]
@mushon @yotammanor 

It works, i'm now getting my information from the "kikar hamedina" API.
